chatroom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('stackflow.urls')),
    path('api/',include('stackflow.api.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stackflow/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.getRoutes),
    path('rooms/',views.getRooms),
    path('rooms/<str:pk>/',views.getRoom),

]

stackflow/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('login',views.loginUser,name='login'),
    path('logout',views.logoutUser,name='logout'),
    path('register',views.registerUser,name='register'),
    path('editProfile',views.editUserProfile,name='editProfile'),
    path('room/<str:pk>/',views.room,name='room'),
    path('userProfile/<str:pk>/',views.userProfile,name='userProfile'),
    path('createRoom',views.createRoom,name='createRoom' ),
    path('updateRoom/<str:pk>/',views.updateRoom,name='updateRoom' ),
    path('deleteRoom/<str:pk>/',views.deleteRoom,name='deleteRoom'),
    path('deleteMessage/<str:pk>/',views.deleteMessage,name='deleteMessage'),

]

stackflow/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    name=models.CharField(max_length=200,null=True)
    email=models.EmailField(unique=True,null=True)
    bio=models.TextField(null=True)

    avator=models.ImageField(null=True,default="defaultUserImg.jpg")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
class Topic(models.Model):
    name=models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class Room(models.Model):
    host=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    topic=models.ForeignKey(Topic,on_delete=models.SET_NULL,null=True)
    name=models.CharField(max_length=255)
    description=models.TextField(null=True,blank=True)
    participants=models.ManyToManyField(User,related_name='participants',blank=True)
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=['-updated','-created']

    def __str__(self):
        return self.name

class Message(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    room=models.ForeignKey(Room,on_delete=models.CASCADE)
    body=models.TextField()
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=['-updated','-created']

    def __str__(self):
        return self.body[0:50]
    

stackflow/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from stackflow.models import Room
from .serializers import RoomSerializer

@api_view(['GET'])
def getRoutes(request):
    routes=[
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms/:id',
    ]
    return Response(routes)

@api_view(['GET'])
def getRooms(request):
    rooms=Room.objects.all()
    serializer=RoomSerializer(rooms,many=True)
    return Response(serializer.data)

@api_view(['GET'])
def getRoom(request,pk):
    room=Room.objects.get(id=pk)
    serializer=RoomSerializer(room,many=False)
    return Response(serializer.data)

stackflow/views.py
from django.shortcuts import render,redirect
from django.contrib import messages 
from django.db.models import Q
from django.http import HttpResponse
from .models import Room,Topic,Message,User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from .form import RoomForm,UserFrom,MyUserCreationForm

def loginUser(request):
    page='login'
    statusLogin=False
    messageLogin=''
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == "POST":
        email=request.POST.get('email','').strip().lower()
        password=request.POST.get('password','')

        try:
            user=User.objects.get(email=email)
        except:
            messageLogin='invlaid user!'
            statusLogin=True
        
        user=authenticate(request,email=email,password=password)
        if user is not None:
            login(request,user)
            return redirect('home')
        else:
            messageLogin=('Username OR password does not exit')
            statusLogin=True
    context={'page':page,'statusLogin':statusLogin,'messageLogin':messageLogin}
    return render(request,'login.html',context)

def logoutUser(request):
    logout(request)
    return redirect('home')

def registerUser(request):
    page='register'
    statusRegister=False
    messageRegister=""
    form=MyUserCreationForm()
    
    if request.method == 'POST':
        print(request.POST)  # Print the entire POST data in the terminal
        print("Username:", request.POST.get("username"))  # Print a specific field
        print("Email:", request.POST.get("email"))
        print("Password:", request.POST.get("password1"))
        form=MyUserCreationForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.username=user.username.strip().lower()
            user.save()
            login(request,user)
            return redirect('home')
        else:
            statusRegister=True
            messageRegister=('An error occurred during registration')
    context={'form':form,'page':page,'statusRegister':statusRegister,'messageRegister':messageRegister}
    return render(request,'login.html',context)

def home(request):
    q=request.GET.get('q') if request.GET.get('q') != None else ''
    rooms=Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )
    room_count=rooms.count()
    topics=Topic.objects.all()
    room_messages=Message.objects.filter(Q(room__topic__name__icontains=q))
    context={'rooms':rooms,'topics':topics,'room_count':room_count,'room_messages':room_messages}
    return render(request,'home.html',context)

def room(request,pk):
    room=Room.objects.get(id=pk)
    room_messages=room.message_set.all()
    participants=room.participants.all()
    if request.method == 'POST':
        message=Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get('body')
        )
        room.participants.add(request.user)
        return redirect('room',pk=room.id)
    context={'room':room,'room_messages':room_messages,'participants':participants}
    return render(request,'room.html',context)

def userProfile(request,pk):
    user=User.objects.get(id=pk)
    rooms=user.room_set.all()
    room_messages=user.message_set.all()
    topics=Topic.objects.all()
    context={'user':user,'rooms':rooms,'room_messages':room_messages,'topics':topics}
    return render(request,'profile.html',context)

@login_required(login_url='login')
def editUserProfile(request):
    user=request.user
    form=UserFrom(instance=user)
    if request.method == 'POST':
        form=UserFrom(request.POST,request.FILES,instance=user)
        if form.is_valid():
            form.save()
            return redirect('userProfile',pk=user.id)
    context={'form':form}
    return render(request,'user_profile.html',context)

@login_required(login_url='login')
def createRoom(request):
    form=RoomForm()
    topics=Topic.objects.all()
    header='Create Room'
    if request.method == "POST":
        topic_name=request.POST.get('topic')
        topic, created=Topic.objects.get_or_create(name=topic_name)

        Room.objects.create(
            host=request.user,
            topic=topic,
            name=request.POST.get('name'),
            description=request.POST.get('description'),
        )
        return redirect('home')
    context={'form':form,'topics':topics,'header':header}
    return render(request,'room_form.html',context)

@login_required(login_url='login')
def updateRoom(request,pk):
    room=Room.objects.get(id=pk)
    form=RoomForm(instance=room)
    topics=Topic.objects.all()
    header='Update Room'
    if request.user != room.host:
        return HttpResponse('Your not the host of this room!!')
    if request.method=="POST":
        topic_name=request.POST.get('topic')
        topic, created=Topic.objects.get_or_create(name=topic_name)
        room.name=request.POST.get('name')
        room.topic=topic
        room.description=request.POST.get('description')
        room.save()
        return redirect('home')
    context={'form':form,'topics':topics,'room':room,'header':header}
    return render(request,'room_form.html',context)

@login_required(login_url='login')
def deleteRoom(request,pk):
    room=Room.objects.get(id=pk)
    if request.method=='POST':
        room.delete()
        return redirect('home')
    return render(request,'delete.html',{'obj':room}) 

@login_required(login_url='login')
def deleteMessage(request,pk):
    message=Message.objects.get(id=pk)
    
    if request.user != message.user:
        return HttpResponse('Your are not allowed to here')
    if request.method == 'POST':
        message.delete()
        return redirect('home')
    return render(request,'delete.html',{'obj':message}) 

stackflow/templates/activity_component.html
<button class="btn btn-primary w-100 d-md-none mb-3" type="button" data-bs-toggle="collapse" data-bs-target="#activityMenu">Recent Activity <i class="bi bi-caret-down-square"></i></button>
{% load static %}
<div id="activityMenu" class="collapse d-md-block mt-md-4" >
    <h4 class="d-none d-md-block p-lg-2 mb-0 text-start">Recent Activities🔻</h4>
    <div class="card mb-3 bg-secondary text-white">
        <div class="card-body activity-card mt-0">
        {% if room_messages %}
            <div class="overflow-auto" style="max-height: 90vh;">
            {% for message in room_messages %}
            <div class="mb-3 p-2 border-bottom">
                <div class="d-flex text-info"> 
                    <div class="">
                        <a href="{% url 'userProfile' message.user.id %}" class="card-subtitle text-white fs-5 text-decoration-none">
                            <img src="{{message.user.avator.url}}" class="rounded-circle border border-secondary" width="30" height="30">
                            <sub>@</sub>{{message.user.username}}
                        </a>
                        <span class="text-white"><sub>{{message.created | timesince}}</sub></span>
                    </div>
                    {% if request.user == message.user%}
                    <a href="{% url 'deleteMessage' message.id %}" class="btn btn-sm text-white ms-lg-auto ms-md-auto align-self-center"><i class="bi bi-x fs-5"></i></a>
                    {% endif %}
                </div>
                <p class="d-block text-white">replied to <a href="{% url 'room' message.room.id %}" class="badge bg-success text-decoration-none">{{message.room}}</a> </p>
                <p class="mb-1 rounded shadow p-3 bg-white text-dark mb-3">{{message.body}}</p>
            </div>
            {% endfor %}
            </div>
        </div>
        {% else %}
        <div class="">
            <p class="mb-1 rounded shadow p-3 bg-white text-dark mb-3">No Recent Activities</p>
        </div>
        {% endif %}
    </div>
</div>

stackflow/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>delete</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body>
    {% extends 'main.html' %}
    {% block content %}

    <div class=" container d-flex justify-content-center mt-5">
        <div class="alert alert-danger w-100 w-auto h-50 mt-5">
            <form method="POST" action="" class="">
                {%  csrf_token %}
                <div class="d-flex justify-content-center gap-2 fs-3" role="alert">
                    <div class="mt-3">
                        <h4 class="">Are you sure to delete?</h4>
                        <p class="">{{obj}}</p>
                    </div>          
                </div>
                <div class="d-flex justify-content-end gap-3 mt-5">
                    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-warning">Cancel</a>
                    <input type="submit" class="btn btn-danger" value="confirm">
                </div>
            </form>
        </div>
    </div>
    {% endblock content%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

stackflow/templates/feed_component.html
<div class="overflow-auto" style="max-height: 100vh;">
    {% for room in rooms %}
    <div class="card mb-1 bg-dark text-white" >
        <div class="card-body ">
            <div class="d-flex justify-content-between gap-3">
                 <a href="{% url 'userProfile' room.host.id %}" class="card-subtitle text-white fs-5 text-decoration-none">
                    <div class=" d-flex justify-content-start">
                        <img src="{{room.host.avator.url}}" class="rounded-circle border border-secondary" width="30" height="30">
                        <div class="">
                            <sub>@</sub>{{ room.host.username }}<sub> ..host</sub>
                        </div>
                    </div>
                </a>
                <div class="d-flex justify-content-end gap-3">
                    {% if request.user == room.host %}
                    <a href="{% url 'updateRoom' room.id %}" class="btn btn-sm btn-warning"><i class="bi bi-pencil"></i></a>
                    <a href="{% url 'deleteRoom' room.id %}" class="btn btn-sm btn-danger"><i class="bi bi-trash"></i></a>
                    {% endif %}
                </div>
            </div>
            <hr class="border border-white border-1 opacity-50" width="20%">
            <h4 class="card-title"><i class="bi bi-house-check fs-3"></i> .. <a href="{% url 'room' room.id %}" class=" text-decoration-none ">{{ room.name }}</a></h4>
            <p class="card-text">{{ room.description|slice:":200" }}....</p>
            <hr class="border border-white border-1 opacity-50">
            <div class="d-flex justify-content-between">
                <span><i class="bi bi-people"></i> {{room.participants.all.count}} joined</span>
                <span class="badge bg-info">{{ room.topic.name }}</span>
            </div>
           
        </div>
    </div>
{% endfor %}
</div>

stackflow/templates/footer.html
<footer class="bg-dark text-white text-center text-lg-start mt-5 mb-0">
    <div class="container p-4 mb-0">
        <div class="row">
            <!-- About Section -->
            <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
                <h5 class="text-uppercase">About Us</h5>
                <p>
                    A platform to explore and discuss various topics. Join the community and start engaging!
                </p>
            </div>

            <!-- Social Media Links -->
            <div class="col-lg-4 col-md-12 mb-4 mb-md-0 text-center">
                <h5 class="text-uppercase">Follow Us</h5>
                <a href="#" class="text-white me-3"><i class="bi bi-facebook"></i></a>
                <a href="#" class="text-white me-3"><i class="bi bi-twitter"></i></a>
                <a href="#" class="text-white me-3"><i class="bi bi-instagram"></i></a>
                <a href="#" class="text-white"><i class="bi bi-linkedin"></i></a>
            </div>
        </div>
    </div>

    <!-- Copyright -->
    <div class="text-center p-3 bg-secondary">
        © {{ 2025 }} Stackflow. All rights reserved.
    </div>
</footer>

stackflow/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StackFlow</title>
    <link rel="icon" type="image/x-icon" href="/static/images/stacked-files.jpg">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/style.css" class="">
</head>
<body>
    {% extends 'main.html' %}
    {% block content %}
    <div class="container-fluid " >
        <div class="row d-flex justify-content-around align-items-stretch ">
            <!-- This Browse Topics left side of the main page -->
            <div class="col-12 col-md-3 col-lg-2 p-3 mt-lg-5 mt-md-5 d-flex flex-column">
                {% include 'topics_component.html' %}
            </div>

            <!-- This room center of the main page -->
            <div   class="col-12 col-md-6 col-lg-7 p-3 ">
                <div class="d-lg-flex justify-content-between">
                    <h5>Totally {{ room_count }} rooms available...</h5>
                    <a href="{% url 'createRoom' %}" class="btn btn-primary mb-3 sticky-top">Create room ➕</a>
                </div>
                {% include 'feed_component.html' %}
            </div>

            <!-- This Activity right side of the main page -->
            <div  class="col-12 col-md-3 col-lg-3 p-3 mt-lg-3 mt-md-3 d-flex flex-column ">
                    {% include 'activity_component.html' %}
            </div>
        </div>
    </div>
    {% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

stackflow/templates/login.html
{% extends 'main.html' %}

{% block content %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-12 text-center">
                <!-- Nav Pills -->
                <ul class="nav nav-pills nav-justified w-25 mx-auto gap-3" id="pills-tab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <a class="nav-link {% if page == 'login' %}active{% endif %}" id="tab-login" 
                            data-bs-toggle="pill" href="#pills-login" role="tab" aria-controls="pills-login" 
                            aria-selected="true">Login</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link {% if page == 'register' %}active{% endif %}" id="tab-register" 
                            data-bs-toggle="pill" href="#pills-register" role="tab" aria-controls="pills-register" 
                            aria-selected="false">Register</a>
                    </li>
                </ul>
            </div>

            <!-- Login & Register Forms -->
            <div class="col-12 col-md-8 col-lg-6">
                <div class="tab-content mt-4">
                    <!-- Login Form -->
                    <div class="tab-pane fade {% if page == 'login' %}show active{% endif %}" id="pills-login">
                        <form method="POST" action="" class="p-3">
                            {% csrf_token %}
                            
                            <!-- Social Login -->
                            <div class="text-center mb-3">
                                <p>Sign in with:</p>
                                <button type="button" class="btn btn-link btn-floating mx-1">
                                    <i class="bi bi-facebook"></i>
                                </button>
                                <button type="button" class="btn btn-link btn-floating mx-1">
                                    <i class="bi bi-google"></i>
                                </button>
                                <button type="button" class="btn btn-link btn-floating mx-1">
                                    <i class="bi bi-twitter-x"></i>
                                </button>
                                <button type="button" class="btn btn-link btn-floating mx-1">
                                    <i class="bi bi-github"></i>
                                </button>
                            </div>

                            <p class="text-center">or:</p>

                            <!-- Input Fields -->
                            <div class="row justify-content-center">
                                <div class="col-12 col-sm-10 col-md-8">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="loginName" name="email" placeholder="Username">
                                        <label for="loginName">Email</label>
                                    </div>

                                    <div class="form-floating mb-3">
                                        <input type="password" id="loginPassword" class="form-control" name="password" placeholder="Password">
                                        <label for="loginPassword">Password</label>
                                    </div>
                                </div>
                            </div>

                            <!-- Buttons -->
                            <div class="d-flex justify-content-center gap-3 mt-4">
                                <button type="submit" class="btn btn-primary px-4">Sign in</button>
                                <a href="{% url 'home' %}" class="btn btn-danger px-4">Back</a>
                            </div>
                        </form>
                        <div class="d-flex justify-content-center mt-3">
                            {% if statusLogin %}
                            <div class="alert alert-danger text-center w-50 fs-5">
                                <h5 class="text-muted">{{messageLogin}}</h5>
                            </div>
                        {% endif %}
                        </div>
                    </div>

                    <!-- Register Form -->
                    <div class="tab-pane fade {% if page == 'register' %}show active{% endif %}" id="pills-register">
                        <div class="container mt-4">
                            <form method="POST" action="{% url 'register' %}">
                                {% csrf_token %}
                                
                                <div class="mb-3">
                                    <label for="id_name" class="form-label">Name</label>
                                    <input type="text" class="form-control" name="name" id="id_name" maxlength="200" required>
                                </div>
                            
                                <div class="mb-3">
                                    <label for="id_username" class="form-label">Username</label>
                                    <input type="text" class="form-control" name="username" id="id_username" maxlength="150" required>
                                    <div class="form-text">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</div>
                                </div>
                            
                                <div class="mb-3">
                                    <label for="id_email" class="form-label">Email</label>
                                    <input type="email" class="form-control" name="email" id="id_email" maxlength="254" required>
                                </div>
                            
                                <div class="mb-3">
                                    <label for="id_password1" class="form-label">Password</label>
                                    <input type="password" class="form-control" name="password1" id="id_password1" required>
                                    <div class="form-text">
                                        <ul>
                                            <li>Your password can’t be too similar to your other personal information.</li>
                                            <li>Your password must contain at least 8 characters.</li>
                                            <li>Your password can’t be a commonly used password.</li>
                                            <li>Your password can’t be entirely numeric.</li>
                                        </ul>
                                    </div>
                                </div>
                            
                                <div class="mb-3">
                                    <label for="id_password2" class="form-label">Confirm Password</label>
                                    <input type="password" class="form-control" name="password2" id="id_password2" required>
                                    <div class="form-text">Enter the same password as before, for verification.</div>
                                </div>
                                <div class="d-flex justify-content-center gap-3">
                                    <button type="submit" class="btn btn-primary w-25">Register</button>
                                    <a href="{% url 'home' %}" class="btn btn-danger w-25">Back</a>
                                </div>
                            </form>
                                
                            <div class="d-flex justify-content-center mt-4">
                                {% if statusRegister %}
                                <div class="alert alert-danger text-center w-75 fs-5">
                                    <h5 class="text-muted">{{messageRegister}}</h5>
                                </div>
                            {% endif %}
                            </div>
                        </div>
                    </div>
                </div> <!-- End Tab Content -->
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <!-- Remember Active Tab After Refresh -->
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            let activeTab = localStorage.getItem("activeTab");

            if (activeTab) {
                let tabElement = document.querySelector(`[href="${activeTab}"]`);
                if (tabElement) {
                    new bootstrap.Tab(tabElement).show();
                }
            }

            document.querySelectorAll('.nav-link').forEach(tab => {
                tab.addEventListener("click", function () {
                    localStorage.setItem("activeTab", this.getAttribute("href"));
                });
            });
        });
    </script>
</body>
</html>
{% endblock content %}

stackflow/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stackflow</title>

</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    {% include 'footer.html'%}
</body>
</html>

stackflow/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Navigation Bar</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary fs-5 p-0">
        <div class="container-fluid bg-primary-subtle">
            <div class="">
                <img src="/static/images/logo.png" alt="" class="mb-2" width="30" height="30"><a class="navbar-brand fs-2 ms-1" href="{% url 'home' %}" >𝚂𝚝𝚊𝚌𝚔𝙵𝚕𝚘𝚠</a>
            </div>
            <button class="navbar-toggler" typ="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button> 
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="d-flex flex-grow-1 justify-content-center w-100">
                    <form method="GET" action="{% url 'home' %}" class="d-flex" name="search">
                        <div class="input-group">
                            <input class="form-control shadow-none" type="text" name="q" placeholder="Search Rooms..." aria-label="Search">
                            <button class="btn bg-white border" type="submit">
                            <i class="bi bi-search"></i></button>
                        </div>
                    </form>
                </div>
                <div class="d-flex flex-grow-1 justify-content-end align-items-center gap-3">
                    {% if request.user.is_authenticated %}
                    <div class="dropdown">
                        <button class="btn btn-dark dropdown-toggle d-flex align-items-center" 
                            type="button" id="dropdownMenuButton" 
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ request.user.avator.url }}" 
                                class="rounded-circle border border-secondary me-2" 
                                width="30" height="30">
                            {{ request.user.username }}
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end bg-body-secondary" aria-labelledby="dropdownMenuButton">
                            <li><a href="{% url 'editProfile' %}" class="dropdown-item">Settings</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a href="{% url 'logout' %}" class="dropdown-item text-danger">Logout</a></li>
                        </ul>
                    </div>
                    
                    {% else %}
                    <a href="{% url 'login' %}" class="text-decoration-none text-danger d-flex align-items-center">
                        <i class="bi bi-person-fill-exclamation me-1"></i> Login
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>